logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate: ERROR
    #org.springframework.jdbc: DEBUG
    #org.hibernate.type: TRACE
    #org.springframework.web: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
  resources:
    chain:
      enabled: true
  social:
    facebook:
      appId: 454804811371783
      appSecret: 593c01a75ec0c4eba76f96abff6a069e
    vkontakte:
      appId: 5680310
      appSecret: VkqmRK68x2QjArW6VHjm

googleApiKey: fakeKey